data:
  train_dataset: /gpfs/workdir/blampeyq/res_novae/X_scConcept
  val_dataset: /gpfs/workdir/blampeyq/res_novae/X_scConcept_validation

model_kwargs:
  embedding_name: "X_scConcept"
  background_noise_lambda: 0.1
  sensitivity_noise_std: 0.01
  n_hops_view: 2
  heads: 16
  hidden_size: 256
  output_size: 128
  temperature: 0.1
  num_prototypes: 512
  panel_subset_size: 0

fit_kwargs:
  max_epochs: 50
  lr: 0.0001
  accelerator: "gpu"
  num_workers: 8
  patience: 6
  min_delta: 0.025

post_training:
  n_domains: [15, 20, 25]
  log_metrics: true
  save_h5ad: true
  log_umap: true
  log_domains: true
  delete_X: true
